# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------

CC            = gcc
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(PICFLAGS) $(GENFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -D_REENTRANT -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=500 -Wall -Wno-unused-function -I"../include" -I"../include/sys" -I"../include/dcps/C++/SACPP" -I"." -I"../examples/include" -I"../examples"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.c     = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"." -L"../lib" -Wl,-rpath,\$$ORIGIN -Wl,-rpath,\$$ORIGIN/../lib
CCC           = $(CXX)
MAKEFILE      = Makefile.sacpp_velocitiesdata_types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -O3 -DNDEBUG
LDLIBS        = -l"dcpssacpp" -l"ddskernel" -ldl $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so))))) -lpthread
OBJS          = .obj$(CFG)/VelocitiesData$(OBJEXT) .obj$(CFG)/VelocitiesDataDcps$(OBJEXT) .obj$(CFG)/VelocitiesDataSplDcps$(OBJEXT) .obj$(CFG)/VelocitiesDataDcps_impl$(OBJEXT)
AREXT         = .a
LIB           = $(LTARGETDIR)$(LIBPREFIX)sacpp_velocitiesdata_types$(LIBSUFFIX)$(AREXT)
SOEXT         = .so
SHTARGETDIR   = ./
SHLIB         = $(SHTARGETDIR)$(LIBPREFIX)sacpp_velocitiesdata_types$(LIBSUFFIX)$(SOEXT)
SHFLAGS       = -shared
SRC           = VelocitiesData.cpp VelocitiesDataDcps.cpp VelocitiesDataSplDcps.cpp VelocitiesDataDcps_impl.cpp
LINK.cc       = $(LD) $(LDFLAGS)
DYNAMICFLAGS  = -DOSPL_BUILDEXAMPLE_LIB
EXPORTFLAGS   = $(DYNAMICFLAGS)

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(SHLIB)

$(SHLIB): $(OBJS)
	@$(TESTDIRSTART) "$(SHTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(SHTARGETDIR)"
	$(LINK.cc) $(SHFLAGS) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

$(LIB): $(OBJS)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	$(AR) $(ARFLAGS) $(LIB) $(OBJS) 

GENERATED_DIRTY = VelocitiesData.h VelocitiesData.cpp VelocitiesDataDcps.cpp VelocitiesDataSplDcps.cpp VelocitiesDataDcps_impl.cpp VelocitiesDataDcps_impl.h VelocitiesDataDcps.h ccpp_VelocitiesData.h VelocitiesDataSplDcps.h

export DYLD_LIBRARY_PATH := $(DYLD_LIBRARY_PATH):../../../../../bin:../../../../../lib
export LD_LIBRARY_PATH   := $(LD_LIBRARY_PATH):../../../../../bin:../../../../../lib
export SHLIB_PATH        := $(SHLIB_PATH):../../../../../bin:../../../../../lib
export LIBPATH           := $(LIBPATH):../../../../../bin:../../../../../lib
export PATH              := $(PATH):../../../../../bin:../../../../../lib

.NOTPARALLEL:
VelocitiesData.h VelocitiesData.cpp VelocitiesDataDcps.cpp VelocitiesDataSplDcps.cpp VelocitiesDataDcps_impl.cpp VelocitiesDataDcps_impl.h VelocitiesDataDcps.h ccpp_VelocitiesData.h VelocitiesDataSplDcps.h: ../idl/VelocitiesData.idl
	"../../../../../bin/idlpp" -I "../../../../../etc/idl" -l cpp ../idl/VelocitiesData.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(OBJS): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

.obj$(CFG)/VelocitiesData$(OBJEXT): VelocitiesData.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) VelocitiesData.cpp

.obj$(CFG)/VelocitiesDataDcps$(OBJEXT): VelocitiesDataDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) VelocitiesDataDcps.cpp

.obj$(CFG)/VelocitiesDataSplDcps$(OBJEXT): VelocitiesDataSplDcps.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) VelocitiesDataSplDcps.cpp

.obj$(CFG)/VelocitiesDataDcps_impl$(OBJEXT): VelocitiesDataDcps_impl.cpp
	@$(TESTDIRSTART) ".obj$(CFG)/" $(TESTDIREND) $(MKDIR) ".obj$(CFG)/"
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) VelocitiesDataDcps_impl.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(SHLIB) $(LIB)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) .obj$(CFG)/

check-syntax:
	$(COMPILE.cc) $(EXPORTFLAGS) $(CHK_SOURCES)

