//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: VelocitiesData.cpp
//  Source: idl/VelocitiesData.idl
//  Generated: Tue Oct 31 12:03:13 2017
//  OpenSplice 6.8.2
//  
//******************************************************************

#include "VelocitiesData.h"




