// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_DDS_DCPS_BUILTINTOPICSC_PDC40A_H_
#define _TAO_IDL_DDS_DCPS_BUILTINTOPICSC_PDC40A_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "dds_builtinTopicsC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 1 || TAO_BETA_VERSION != 1
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDS
{

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct Time_t;

  typedef
    ::TAO_Fixed_Var_T<
        Time_t
      >
    Time_t_var;

  typedef
    Time_t &
    Time_t_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  Time_t
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Time_t_var _var_type;
    typedef Time_t_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Long sec;
    ::CORBA::ULong nanosec;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_Time_t;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum SchedulingClassQosPolicyKind
  {
    SCHEDULE_DEFAULT,
    SCHEDULE_TIMESHARING,
    SCHEDULE_REALTIME
  };

  typedef SchedulingClassQosPolicyKind &SchedulingClassQosPolicyKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingClassQosPolicyKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SchedulingClassQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        SchedulingClassQosPolicy
      >
    SchedulingClassQosPolicy_var;

  typedef
    SchedulingClassQosPolicy &
    SchedulingClassQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SchedulingClassQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SchedulingClassQosPolicy_var _var_type;
    typedef SchedulingClassQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::SchedulingClassQosPolicyKind kind;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingClassQosPolicy;

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum SchedulingPriorityQosPolicyKind
  {
    PRIORITY_RELATIVE,
    PRIORITY_ABSOLUTE
  };

  typedef SchedulingPriorityQosPolicyKind &SchedulingPriorityQosPolicyKind_out;

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingPriorityQosPolicyKind;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SchedulingPriorityQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        SchedulingPriorityQosPolicy
      >
    SchedulingPriorityQosPolicy_var;

  typedef
    SchedulingPriorityQosPolicy &
    SchedulingPriorityQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SchedulingPriorityQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SchedulingPriorityQosPolicy_var _var_type;
    typedef SchedulingPriorityQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::SchedulingPriorityQosPolicyKind kind;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingPriorityQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SchedulingQosPolicy;

  typedef
    ::TAO_Fixed_Var_T<
        SchedulingQosPolicy
      >
    SchedulingQosPolicy_var;

  typedef
    SchedulingQosPolicy &
    SchedulingQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SchedulingQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SchedulingQosPolicy_var _var_type;
    typedef SchedulingQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::SchedulingClassQosPolicy scheduling_class;
    DDS::SchedulingPriorityQosPolicy scheduling_priority_kind;
    ::CORBA::Long scheduling_priority;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SchedulingQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct ViewKeyQosPolicy;

  typedef
    ::TAO_Var_Var_T<
        ViewKeyQosPolicy
      >
    ViewKeyQosPolicy_var;

  typedef
    ::TAO_Out_T<
        ViewKeyQosPolicy
      >
    ViewKeyQosPolicy_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  ViewKeyQosPolicy
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef ViewKeyQosPolicy_var _var_type;
    typedef ViewKeyQosPolicy_out _out_type;

    static void _tao_any_destructor (void *);
    
    ::CORBA::Boolean use_key_list;
    DDS::StringSeq key_list;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_ViewKeyQosPolicy;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DataReaderViewQos;

  typedef
    ::TAO_Var_Var_T<
        DataReaderViewQos
      >
    DataReaderViewQos_var;

  typedef
    ::TAO_Out_T<
        DataReaderViewQos
      >
    DataReaderViewQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DataReaderViewQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DataReaderViewQos_var _var_type;
    typedef DataReaderViewQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::ViewKeyQosPolicy view_keys;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DataReaderViewQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DomainParticipantFactoryQos;

  typedef
    ::TAO_Fixed_Var_T<
        DomainParticipantFactoryQos
      >
    DomainParticipantFactoryQos_var;

  typedef
    DomainParticipantFactoryQos &
    DomainParticipantFactoryQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DomainParticipantFactoryQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DomainParticipantFactoryQos_var _var_type;
    typedef DomainParticipantFactoryQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::EntityFactoryQosPolicy entity_factory;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DomainParticipantFactoryQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DomainParticipantQos;

  typedef
    ::TAO_Var_Var_T<
        DomainParticipantQos
      >
    DomainParticipantQos_var;

  typedef
    ::TAO_Out_T<
        DomainParticipantQos
      >
    DomainParticipantQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DomainParticipantQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DomainParticipantQos_var _var_type;
    typedef DomainParticipantQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::UserDataQosPolicy user_data;
    DDS::EntityFactoryQosPolicy entity_factory;
    DDS::SchedulingQosPolicy watchdog_scheduling;
    DDS::SchedulingQosPolicy listener_scheduling;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DomainParticipantQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct TopicQos;

  typedef
    ::TAO_Var_Var_T<
        TopicQos
      >
    TopicQos_var;

  typedef
    ::TAO_Out_T<
        TopicQos
      >
    TopicQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  TopicQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef TopicQos_var _var_type;
    typedef TopicQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::TopicDataQosPolicy topic_data;
    DDS::DurabilityQosPolicy durability;
    DDS::DurabilityServiceQosPolicy durability_service;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::HistoryQosPolicy history;
    DDS::ResourceLimitsQosPolicy resource_limits;
    DDS::TransportPriorityQosPolicy transport_priority;
    DDS::LifespanQosPolicy lifespan;
    DDS::OwnershipQosPolicy ownership;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_TopicQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DataWriterQos;

  typedef
    ::TAO_Var_Var_T<
        DataWriterQos
      >
    DataWriterQos_var;

  typedef
    ::TAO_Out_T<
        DataWriterQos
      >
    DataWriterQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DataWriterQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DataWriterQos_var _var_type;
    typedef DataWriterQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::DurabilityQosPolicy durability;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::HistoryQosPolicy history;
    DDS::ResourceLimitsQosPolicy resource_limits;
    DDS::TransportPriorityQosPolicy transport_priority;
    DDS::LifespanQosPolicy lifespan;
    DDS::UserDataQosPolicy user_data;
    DDS::OwnershipQosPolicy ownership;
    DDS::OwnershipStrengthQosPolicy ownership_strength;
    DDS::WriterDataLifecycleQosPolicy writer_data_lifecycle;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DataWriterQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct PublisherQos;

  typedef
    ::TAO_Var_Var_T<
        PublisherQos
      >
    PublisherQos_var;

  typedef
    ::TAO_Out_T<
        PublisherQos
      >
    PublisherQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  PublisherQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PublisherQos_var _var_type;
    typedef PublisherQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::PresentationQosPolicy presentation;
    DDS::PartitionQosPolicy partition;
    DDS::GroupDataQosPolicy group_data;
    DDS::EntityFactoryQosPolicy entity_factory;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_PublisherQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct DataReaderQos;

  typedef
    ::TAO_Var_Var_T<
        DataReaderQos
      >
    DataReaderQos_var;

  typedef
    ::TAO_Out_T<
        DataReaderQos
      >
    DataReaderQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  DataReaderQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef DataReaderQos_var _var_type;
    typedef DataReaderQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::DurabilityQosPolicy durability;
    DDS::DeadlineQosPolicy deadline;
    DDS::LatencyBudgetQosPolicy latency_budget;
    DDS::LivelinessQosPolicy liveliness;
    DDS::ReliabilityQosPolicy reliability;
    DDS::DestinationOrderQosPolicy destination_order;
    DDS::HistoryQosPolicy history;
    DDS::ResourceLimitsQosPolicy resource_limits;
    DDS::UserDataQosPolicy user_data;
    DDS::OwnershipQosPolicy ownership;
    DDS::TimeBasedFilterQosPolicy time_based_filter;
    DDS::ReaderDataLifecycleQosPolicy reader_data_lifecycle;
    DDS::SubscriptionKeyQosPolicy subscription_keys;
    DDS::ReaderLifespanQosPolicy reader_lifespan;
    DDS::ShareQosPolicy share;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_DataReaderQos;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct SubscriberQos;

  typedef
    ::TAO_Var_Var_T<
        SubscriberQos
      >
    SubscriberQos_var;

  typedef
    ::TAO_Out_T<
        SubscriberQos
      >
    SubscriberQos_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  SubscriberQos
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef SubscriberQos_var _var_type;
    typedef SubscriberQos_out _out_type;

    static void _tao_any_destructor (void *);
    
    DDS::PresentationQosPolicy presentation;
    DDS::PartitionQosPolicy partition;
    DDS::GroupDataQosPolicy group_data;
    DDS::EntityFactoryQosPolicy entity_factory;
    DDS::ShareQosPolicy share;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_SubscriberQos;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::Time_t>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::Time_t,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::SchedulingClassQosPolicyKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::SchedulingClassQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::SchedulingClassQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::SchedulingClassQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:898

  template<>
  class Arg_Traits< ::DDS::SchedulingPriorityQosPolicyKind>
    : public
        Basic_Arg_Traits_T<
            ::DDS::SchedulingPriorityQosPolicyKind,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::SchedulingPriorityQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::SchedulingPriorityQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::SchedulingQosPolicy>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::SchedulingQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::ViewKeyQosPolicy>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::ViewKeyQosPolicy,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DataReaderViewQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::DataReaderViewQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DomainParticipantFactoryQos>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::DomainParticipantFactoryQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DomainParticipantQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::DomainParticipantQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::TopicQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::TopicQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DataWriterQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::DataWriterQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::PublisherQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::PublisherQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::DataReaderQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::DataReaderQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:941

  template<>
  class Arg_Traits< ::DDS::SubscriberQos>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::SubscriberQos,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::Time_t &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::Time_t*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::Time_t *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::Time_t *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::Time_t &); // copying version
 void operator<<= (::CORBA::Any &, DDS::Time_t*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::Time_t *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::Time_t *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::SchedulingClassQosPolicyKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::SchedulingClassQosPolicyKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::SchedulingClassQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingClassQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::SchedulingClassQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::SchedulingClassQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::SchedulingClassQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::SchedulingClassQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SchedulingClassQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SchedulingClassQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingClassQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SchedulingClassQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
  

   void operator<<= (::CORBA::Any &, ::DDS::SchedulingPriorityQosPolicyKind);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::SchedulingPriorityQosPolicyKind &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, DDS::SchedulingPriorityQosPolicyKind);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingPriorityQosPolicyKind &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::SchedulingPriorityQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::SchedulingPriorityQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::SchedulingPriorityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::SchedulingPriorityQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SchedulingPriorityQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SchedulingPriorityQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingPriorityQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SchedulingPriorityQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::SchedulingQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::SchedulingQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::SchedulingQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::SchedulingQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SchedulingQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SchedulingQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SchedulingQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SchedulingQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::ViewKeyQosPolicy &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::ViewKeyQosPolicy*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::ViewKeyQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::ViewKeyQosPolicy *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::ViewKeyQosPolicy &); // copying version
 void operator<<= (::CORBA::Any &, DDS::ViewKeyQosPolicy*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::ViewKeyQosPolicy *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::ViewKeyQosPolicy *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DataReaderViewQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DataReaderViewQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DataReaderViewQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DataReaderViewQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DataReaderViewQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DataReaderViewQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DataReaderViewQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DataReaderViewQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DomainParticipantFactoryQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DomainParticipantFactoryQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DomainParticipantFactoryQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DomainParticipantFactoryQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DomainParticipantFactoryQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DomainParticipantFactoryQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DomainParticipantFactoryQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DomainParticipantFactoryQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DomainParticipantQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DomainParticipantQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DomainParticipantQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DomainParticipantQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DomainParticipantQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DomainParticipantQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DomainParticipantQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DomainParticipantQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::TopicQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::TopicQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::TopicQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::TopicQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::TopicQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::TopicQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::TopicQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::TopicQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DataWriterQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DataWriterQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DataWriterQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DataWriterQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DataWriterQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DataWriterQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DataWriterQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DataWriterQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::PublisherQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::PublisherQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::PublisherQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::PublisherQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::PublisherQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::PublisherQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::PublisherQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::PublisherQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::DataReaderQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::DataReaderQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::DataReaderQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::DataReaderQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::DataReaderQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::DataReaderQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::DataReaderQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::DataReaderQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace DDS
{
   void operator<<= (::CORBA::Any &, const ::DDS::SubscriberQos &); // copying version
   void operator<<= (::CORBA::Any &, ::DDS::SubscriberQos*); // noncopying version
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::DDS::SubscriberQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const ::DDS::SubscriberQos *&);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const DDS::SubscriberQos &); // copying version
 void operator<<= (::CORBA::Any &, DDS::SubscriberQos*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DDS::SubscriberQos *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const DDS::SubscriberQos *&);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::Time_t &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::Time_t &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::SchedulingClassQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::SchedulingClassQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SchedulingClassQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SchedulingClassQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::SchedulingPriorityQosPolicyKind _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::SchedulingPriorityQosPolicyKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SchedulingPriorityQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SchedulingPriorityQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SchedulingQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SchedulingQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::ViewKeyQosPolicy &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::ViewKeyQosPolicy &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DataReaderViewQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DataReaderViewQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DomainParticipantFactoryQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DomainParticipantFactoryQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DomainParticipantQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DomainParticipantQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::TopicQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::TopicQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DataWriterQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DataWriterQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::PublisherQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::PublisherQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::DataReaderQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::DataReaderQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SubscriberQos &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SubscriberQos &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "dds_dcps_builtintopicsC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

