//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ContentFilteredTopicData.cpp
//  Source: ../../idl/ContentFilteredTopicData.idl
//  Generated: Mon Oct 23 17:11:30 2017
//  OpenSplice 6.8.2
//  
//******************************************************************

#include "ContentFilteredTopicData.h"




