//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ContentFilteredTopicData.h
//  Source: ../../idl/ContentFilteredTopicData.idl
//  Generated: Mon Oct 23 17:11:30 2017
//  OpenSplice 6.8.2
//  
//******************************************************************
#ifndef _CONTENTFILTEREDTOPICDATA_H_
#define _CONTENTFILTEREDTOPICDATA_H_

#include "sacpp_mapping.h"


namespace StockMarket
{
   struct Stock;

   struct Stock
   {
         DDS::String_mgr ticker;
         DDS::Float price;
   };

   typedef DDS_DCPSStruct_var < Stock> Stock_var;
   typedef DDS_DCPSStruct_out < Stock> Stock_out;
}




#endif
