//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: WaitSetData.cpp
//  Source: ../../idl/WaitSetData.idl
//  Generated: Mon Oct 23 17:10:19 2017
//  OpenSplice 6.8.2
//  
//******************************************************************

#include "WaitSetData.h"




