//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_rmi.h
//  Source: /home/dds/OvernightTests/overnight/osplo/tags/OSPL_V6_8_2-RC2/ubuntu1204-64/x86_64.linux-release-notest/build/src/services/rmi/idl/dds_rmi.idl
//  Generated: Thu Jul 27 00:53:34 2017
//  OpenSplice 6.8.2
//  
//******************************************************************
#ifndef _DDS_RMI_H_
#define _DDS_RMI_H_

#include "sacpp_mapping.h"


namespace DDS_RMI
{
   struct Identification;
   struct Definition;
   struct Client_Identification;
   struct Request_Header;
   const DDS::Long Diffusion_Service = (DDS::Long) -1L;

   struct Identification
   {
         DDS::String_mgr server_class;
         DDS::String_mgr server_impl;
         DDS::Long server_instance;
   };

   typedef DDS_DCPSStruct_var < Identification> Identification_var;
   typedef DDS_DCPSStruct_out < Identification> Identification_out;
   struct method_list_uniq_ {};
   typedef DDS_DCPSUStrSeqT <struct method_list_uniq_> method_list;
   typedef DDS_DCPSUStrSeq_var < method_list> method_list_var;
   typedef DDS_DCPSUStrSeq_out < method_list> method_list_out;

   struct Definition
   {
         DDS::String_mgr server_class;
         method_list server_api;
   };

   typedef DDS_DCPSStruct_var < Definition> Definition_var;
   typedef DDS_DCPSStruct_out < Definition> Definition_out;

   struct Client_Identification
   {
         DDS::String_mgr client_impl;
         DDS::Long client_instance;
         DDS::ULong request_id;
   };

   typedef DDS_DCPSStruct_var < Client_Identification> Client_Identification_var;
   typedef DDS_DCPSStruct_out < Client_Identification> Client_Identification_out;

   struct Request_Header
   {
         Identification service_id;
         Client_Identification client_id;
   };

   typedef DDS_DCPSStruct_var < Request_Header> Request_Header_var;
   typedef DDS_DCPSStruct_out < Request_Header> Request_Header_out;
}




#endif
