//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: HelloWorldData.cpp
//  Source: ../../idl/HelloWorldData.idl
//  Generated: Mon Oct 23 17:10:01 2017
//  OpenSplice 6.8.2
//  
//******************************************************************

#include "HelloWorldData.h"




