#include "Throughput_DCPS.hpp"

#include <v_copyIn.h>
#include <v_topic.h>
#include <os_stdlib.h>
#include <string.h>
#include <os_report.h>

v_copyin_result
__ThroughputModule_DataType__copyIn(
    c_base base,
    const class ::ThroughputModule::DataType *from,
    struct _ThroughputModule_DataType *to)
{
    v_copyin_result result = V_COPYIN_RESULT_OK;
    (void) base;

    to->count = (c_ulonglong)from->count_;
    {
/* Code generated by /home/dds/OvernightTests/overnight/ospli/tags/OSPL_V6_8_2-RC2/ubuntu1204-64/x86_64.linux-release-notest-inner/build/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 826 */

        static c_type type0 = NULL;
        c_type subtype0;
        c_ulong length0;
        c_octet *dest0;
        const ::ThroughputModule::DataType::_payload_seq *src = &from->payload_;

        if (type0 == NULL) {
            subtype0 = c_type(c_metaResolve (c_metaObject(base), "c_octet"));
            type0 = c_metaSequenceTypeNew(c_metaObject(base),"C_SEQUENCE<c_octet>",subtype0,0);
            c_free(subtype0);
        }
        length0 = (c_ulong)(*src).size();
#ifdef OSPL_BOUNDS_CHECK
         dest0 = (c_octet *)c_newSequence_s(c_collectionType(type0),length0);
         if(dest0 != NULL) {
            /* Code generated by /home/dds/OvernightTests/overnight/ospli/tags/OSPL_V6_8_2-RC2/ubuntu1204-64/x86_64.linux-release-notest-inner/build/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 2025 */
            if(length0 > 0)
            {
                const c_octet *buf0;
                buf0 = reinterpret_cast<const c_octet *>(&((*src)[0]));
                memcpy (dest0,buf0,length0* sizeof(*dest0));
            }
            to->payload = (c_sequence)dest0;
         } else {
             result = V_COPYIN_RESULT_OUT_OF_MEMORY;
          }
#else
        dest0 = (c_octet *)c_newSequence_s(c_collectionType(type0),length0);
        if(dest0 != NULL) {
            /* Code generated by /home/dds/OvernightTests/overnight/ospli/tags/OSPL_V6_8_2-RC2/ubuntu1204-64/x86_64.linux-release-notest-inner/build/src/tools/idlpp/code/idl_genCorbaCxxCopyin.c at line 2025 */
            if(length0 > 0)
            {
                const c_octet *buf0;
                buf0 = reinterpret_cast<const c_octet *>(&((*src)[0]));
                memcpy (dest0,buf0,length0* sizeof(*dest0));
            }
            to->payload = (c_sequence)dest0;
        } else {
            result = V_COPYIN_RESULT_OUT_OF_MEMORY;
        }
#endif
    }
    return result;
}

void
__ThroughputModule_DataType__copyOut(
    const void *_from,
    void *_to)
{
    const struct _ThroughputModule_DataType *from = (const struct _ThroughputModule_DataType *)_from;
    class ::ThroughputModule::DataType *to = (class ::ThroughputModule::DataType *)_to;
    to->count((uint64_t)from->count);
    {
        long size0;
        const c_octet *src0 = (const c_octet *)from->payload;
        std::vector< uint8_t > *dst = &to->payload();

        size0 = c_arraySize(c_sequence(from->payload));
        to->payload().clear();
        to->payload().reserve(size0);
            (*dst).insert((*dst).end(), src0, src0 + size0);
    }
}

