#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = $(SPLICE_JAVAC)
JAR           = jar
JAVACFLAGS    = $(GENFLAGS)
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(SPLICE_EXTRA_CP):$(CLASSDIR):../../../../jar/dcpssaj5.jar:"
MAKEFILE      = Makefile.saj5_durability_types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)DurabilityData/*$(CLASSEXT) $(CLASSDIR)DurabilityDataSubscriber$(CLASSEXT) $(CLASSDIR)DurabilityDataPublisher$(CLASSEXT)
JARCLASSES    =  DurabilityData/*$(CLASSEXT) DurabilityDataSubscriber$(CLASSEXT) DurabilityDataPublisher$(CLASSEXT)
JAREXT        = .jar
MAINCLASS     = DurabilityDataSubscriber
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)saj5_durability_types$(LIBSUFFIX)$(JAREXT)
MANIFEST      = saj5_durability_types.manifest
JARFLAGS      = cvfm
SRC           = DurabilityData/*.java DurabilityDataSubscriber.java DurabilityDataPublisher.java

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: ../../../../jar/dcpssaj5.jar > $(CLASSDIR)$(MANIFEST)
	echo Main-Class: $(MAINCLASS) >> $(CLASSDIR)$(MANIFEST)

GENERATED_DIRTY = DurabilityData

DurabilityData: ../idl/DurabilityData.idl
	"../../../../bin/idlpp" -I "../../../../etc/idl" -l java ../idl/DurabilityData.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(CLASSES): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)DurabilityData/*$(CLASSEXT): DurabilityData
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) DurabilityData/*.java

$(CLASSDIR)DurabilityDataSubscriber$(CLASSEXT): DurabilityDataSubscriber.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) DurabilityDataSubscriber.java

$(CLASSDIR)DurabilityDataPublisher$(CLASSEXT): DurabilityDataPublisher.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) DurabilityDataPublisher.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

