//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_namedQosTypesDcps.h
//  Source: dds_namedQosTypesDcps.idl
//  Generated: Thu Jul 27 00:46:05 2017
//  OpenSplice 6.8.2
//  
//******************************************************************
#ifndef _DDS_NAMEDQOSTYPESDCPS_H_
#define _DDS_NAMEDQOSTYPESDCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps_builtintopics.h"
#include "dds_dcps.h"
#include "dds_namedQosTypes.h"






#endif
